apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-admin
  labels:
    app: xyz-admin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xyz-admin
  template:
    metadata:
      labels:
        app: xyz-admin
    spec:
      containers:
      - name: xyz-admin
        image: mujah92/xyz-admin-module:{{ build_number }}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always