---
- name: Deploy to Minikube Kubernetes
  hosts: localhost
  connection: local
  become: false
  gather_facts: no
  vars:
    image_name: "mujah92/xyz_tech"
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
    k8s_dir: "{{ workspace }}/k8s"
    kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/config"

  tasks:
    - name: Ensure kubectl is configured
      command: minikube kubectl -- get nodes
      register: kube_check
      changed_when: false
      ignore_errors: yes

    - name: Update image tag in deployment
      replace:
        path: "{{ k8s_dir }}/xyz_tech_deployment.yaml"
        regexp: "mujah92/xyz_tech:.*"
        replace: "mujah92/xyz_tech:{{ build_number }}"

    - name: Deploy to Kubernetes
      command: "minikube kubectl -- apply -f {{ k8s_dir }}/"
      args:
        chdir: "{{ workspace }}"
      register: apply
      changed_when: "'created' in apply.stdout or 'configured' in apply.stdout"

    - name: Get Kubernetes dashboard URL
  command: minikube dashboard --url
  register: k8s_dashboard_url
  changed_when: false

- name: Get application service URL
  command: minikube service xyz-tech-service --url
  register: app_service_url
  changed_when: false

- name: Launch dashboard in background
  command: minikube dashboard
  async: 300  # Allow 5 minutes for dashboard
  poll: 0     # Don't wait for completion

- name: Display all access URLs
  debug:
    msg: |
      ACCESS URLs:
      - Kubernetes Dashboard: {{ k8s_dashboard_url.stdout }}
      - Your Application: {{ app_service_url.stdout }}/xyz_tech
