---
- name: Deploy to Minikube Kubernetes
  hosts: k8s_master
  become: yes
  vars:
    image_name: "mujah92/xyz_tech"
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
    k8s_dir: "{{ workspace }}/k8s"

  tasks:
    - name: Ensure kubectl is configured for Minikube
      command: minikube kubectl -- get nodes
      register: kube_check
      changed_when: false
      ignore_errors: yes

    - name: Configure Minikube context
      command: minikube update-context
      when: kube_check.failed

    - name: Update image tag in deployment
      replace:
        path: "{{ k8s_dir }}/xyz_tech_deployment.yaml"
        regexp: "mujah92/xyz_tech:.*"
        replace: "mujah92/xyz_tech:{{ build_number }}"

    - name: Apply Kubernetes manifests
      k8s:
        state: present
        definition: "{{ lookup('file', item) | from_yaml }}"
      loop:
        - "{{ k8s_dir }}/xyz_tech_deployment.yaml"
        - "{{ k8s_dir }}/xyz_tech_service.yaml"

    - name: Verify deployment
      command: minikube kubectl -- rollout status deployment/xyz-tech
      register: rollout
      until: rollout.stdout.find("successfully rolled out") != -1
      retries: 10
      delay: 5

    - name: Get Minikube service URL
      command: minikube service xyz-tech-service --url
      register: service_url
      changed_when: false

    - name: Display access information
      debug:
        msg: |
          Application deployed successfully!
          Access via: {{ service_url.stdout }}
          Or run: minikube service xyz-tech-service