---
- name: Deploy to Minikube Kubernetes
  hosts: localhost
  connection: local
  become: false
  gather_facts: no
  vars:
    image_name: "mujah92/xyz_tech"
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
    k8s_dir: "{{ workspace }}/k8s"
    kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/config"

  tasks:
    - name: Ensure kubectl is configured
      command: minikube kubectl -- get nodes
      register: kube_check
      changed_when: false
      ignore_errors: yes

    - name: Configure Minikube context if needed
      command: minikube update-context
      when: kube_check.failed
      changed_when: kube_check.failed

    - name: Update image tag in deployment
      replace:
        path: "{{ k8s_dir }}/xyz_tech_deployment.yaml"
        regexp: "mujah92/xyz_tech:.*"
        replace: "mujah92/xyz_tech:{{ build_number }}"

    - name: Apply manifests using minikube
      command: "minikube kubectl -- apply -f {{ k8s_dir }}/"
      args:
        chdir: "{{ workspace }}"
      register: apply
      changed_when: "'created' in apply.stdout or 'configured' in apply.stdout"

    - name: Verify deployment status
      command: minikube kubectl -- rollout status deployment/xyz-tech --timeout=120s
      register: rollout
      until: rollout.rc == 0
      retries: 10
      delay: 10

    - name: Get service access URL
      command: minikube service xyz-tech-service --url
      register: service_url
      changed_when: false

    - name: Show access information
      debug:
        msg: |
          ✅ Deployment Successful!
          🌐 Access your application at: {{ service_url.stdout }}
          🔁 Or run manually: minikube service xyz-tech-service
